### ISSUE TITLE
OSS link in hero has no href value

### ISSUE THREAD

**Issue by stevepolitodesign** [andrewmcodes/personal-website#35]
![andrewm_code_website](https://user-images.githubusercontent.com/5122678/86770476-c121ef80-c01e-11ea-8f12-3940acde78f4.gif)

Site's looking good! I noticed that the "OSS" link on the hero has no `href` value.

**Comment by andrewmcodes** [comment]
Thanks @stevepolitodesign ❤️ 

Fixed in v2.
